List<String> RegisterEnglish = [
  "Sign in",
  "Full name",
  "Name must not be empty",
  "Email Address",
  "Email Address must not be empty",
  "Phone number",
  "Phone number must not be empty",
  "Password",
  "Password must not be empty",
  "Confirm Password",
  "Confirm Password must not be empty",
  "Confirm Password is not matching",
  "Gender",
  "Male",
  "Female",
  "Register now",
  "Or Continue",
  "Error",
  "Please fill up the registration complete form",
  "Password do not match",
  "Email Exist",
];

List<String> RegisterArabic = [
  "تسجيل الدخول",
  "الاسم بالكامل",
  "يجب ألا يكون الاسم فارغًا",
  "عنوان البريد الإلكتروني",
  "يجب ألا يكون عنوان البريد الإلكتروني فارغًا",
  "رقم الهاتف",
  "يجب ألا يكون رقم الهاتف فارغًا",
  "كلمه السر",
  "يجب ألا تكون كلمة المرور فارغة",
  "تأكيد كلمة المرور",
  "تأكيد كلمة المرور يجب ألا يكون فارغًا",
  "تأكيد كلمة المرور غير مطابق",
  "النوع",
  "ذكر",
  "أنثى",
  "سجل الان",
  "أو متابعة",
  "خطأ",
  "يرجى ملء استمارة التسجيل كاملة",
  "كلمة السر غير مطابقة",
  "البريد الإلكتروني موجود",
];