List<String> ViewProfileEnglish = [
  "My Profile",
  "Full name",
  "Name must not be empty",
  "Email Address",
  "Email Address must not be empty",
  "Phone number",
  "Phone number must not be empty",
  "Password",
  "Password must not be empty",
  "Confirm Password",
  "Confirm Password must not be empty",
  "Confirm Password is not matching",
  "Age",
  "Weight",
  "Height",
  "Edit Profile",
  "Age must not be empty",
  "Weight must not be empty",
  "Height must not be empty",
  "Update",
];

List<String> ViewProfileArabic = [
  "ملفي الشخصي",
  "الاسم بالكامل",
  "يجب ألا يكون الاسم فارغًا",
  "عنوان البريد الإلكتروني",
  "يجب ألا يكون عنوان البريد الإلكتروني فارغًا",
  "رقم الهاتف",
  "يجب ألا يكون رقم الهاتف فارغًا",
  "كلمه السر",
  "يجب ألا تكون كلمة المرور فارغة",
  "تأكيد كلمة المرور",
  "تأكيد كلمة المرور يجب ألا يكون فارغًا",
  "تأكيد كلمة المرور غير مطابق",
  "السن",
  "الوزن",
  "الطول",
  "تعديل الملف الشخصي",
  "يجب ألا يكون العمر فارغًا",
  "يجب ألا يكون الوزن فارغًا",
  "يجب ألا يكون الطول فارغًا",
  "تحديث",
];